version: '3'
services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/code
    command: "uvicorn src.asgi:application --host 0.0.0.0 --port 8000"
    #command: "python manage.py runserver 0.0.0.0:8000"
